#pragma once

#include <math.h>
#include <float.h>

typedef struct { float x, y; } vec2;
typedef struct { float x, y, z; } vec3;
typedef struct { float x, y, z, w; } vec4;
typedef struct { int x, y; } ivec2;

static inline vec2 v2(float x, float y) { return (vec2){ x, y }; }
static inline vec3 v3(float x, float y, float z) { return (vec3){ x, y, z }; }
static inline vec4 v4(float x, float y, float z, float w) { return (vec4){ x, y, z, w }; }
static inline ivec2 iv2(int x, int y) { return (ivec2){ x, y }; }

// Splat scalar → vec
static inline vec2 v2s(float s) { return v2(s, s); }
static inline vec3 v3s(float s) { return v3(s, s, s); }

// v.xxy
static inline vec3 xxy(vec3 v) { return v3(v.x, v.x, v.y); }
// v.zy
static inline vec2 zy(vec3 v) { return v2(v.z, v.y); }
// v.yzx
static inline vec3 yzx(vec3 v) { return v3(v.y, v.z, v.x); }
// v.zxy
static inline vec3 zxy(vec3 v) { return v3(v.z, v.x, v.y); }

static inline vec3 v3add(vec3 a, vec3 b) { return v3(a.x+b.x, a.y+b.y, a.z+b.z); }
static inline vec3 v3sub(vec3 a, vec3 b) { return v3(a.x-b.x, a.y-b.y, a.z-b.z); }
static inline vec3 v3mul(vec3 a, vec3 b) { return v3(a.x*b.x, a.y*b.y, a.z*b.z); }
static inline vec3 v3div(vec3 a, vec3 b) { return v3(a.x/b.x, a.y/b.y, a.z/b.z); }
static inline vec3 v3scale(vec3 v, float s) { return v3(v.x*s, v.y*s, v.z*s); }
static inline vec3 v3neg(vec3 v) { return v3(-v.x,-v.y,-v.z); }
static inline vec3 v3adds(vec3 v, float s) { return v3(v.x+s,v.y+s,v.z+s); }

static inline float v3dot(vec3 a, vec3 b) { return a.x*b.x + a.y*b.y + a.z*b.z; }
static inline float v3len(vec3 v) { return sqrtf(v3dot(v, v)); }
static inline vec3  v3norm(vec3 v) { float l=v3len(v); return v3scale(v, l > 0 ? 1.f/l : 0.f); }

static inline vec2 v2add(vec2 a, vec2 b) { return v2(a.x+b.x, a.y+b.y); }
static inline vec2 v2sub(vec2 a, vec2 b) { return v2(a.x-b.x, a.y-b.y); }
static inline vec2 v2mul(vec2 a, vec2 b) { return v2(a.x*b.x, a.y*b.y); }
static inline float v2len(vec2 v) { return sqrtf(v.x*v.x + v.y*v.y); }

static inline float gfract(float x) { return x - floorf(x); }
static inline float gceil(float x) { return ceilf(x); }
static inline float gabs(float x) { return fabsf(x); }
static inline float gsign(float x) { return (x>0)-(x<0); }
static inline float gmin(float a, float b) {
    if (a != a) return b;
    if (b != b) return a;
    return a < b ? a : b;
}
static inline float  gmax(float a, float b) { return a > b ? a : b; }
static inline float  gstep(float edge, float x) { return x >= edge ? 1.f : 0.f; }

static inline vec2 v2fract(vec2 v) { return v2(gfract(v.x), gfract(v.y)); }
static inline vec3 v3fract(vec3 v) { return v3(gfract(v.x), gfract(v.y), gfract(v.z)); }
static inline vec3 v3ceil (vec3 v) { return v3(gceil(v.x), gceil(v.y), gceil(v.z)); }
static inline vec3 v3abs  (vec3 v) { return v3(gabs(v.x), gabs(v.y), gabs(v.z)); }
static inline vec3 v3sign (vec3 v) { return v3(gsign(v.x), gsign(v.y), gsign(v.z)); }
static inline vec3 v3min  (vec3 a, vec3 b) { return v3(gmin(a.x, b.x), gmin(a.y, b.y), gmin(a.z, b.z)); }
static inline vec3 v3max  (vec3 a, vec3 b) { return v3(gmax(a.x, b.x), gmax(a.y, b.y), gmax(a.z, b.z)); }

static inline vec3 v3step(vec3 edge, vec3 x) {
    return v3(gstep(edge.x, x.x), gstep(edge.y, x.y), gstep(edge.z, x.z));
}

static inline vec3 v3fwidth(vec3 p, float pixel_size) {
    /* |dFdx| ≈ |p| * pixel_size — a crude but sufficient screen-space proxy */
    float d = v3len(p) * pixel_size + pixel_size;
    return v3(d, d, d);
}

static inline vec2 rotate2D_diag(float angle) {
    float c = cosf(angle);
    return v2(c, c);
}

static inline float _dot3(float ax,float ay,float az,float bx,float by,float bz){
    return ax * bx + ay * by + az * bz;
}

/// --- Generated by Claude Code ---

static const int _perm[512] = {
    151,160,137,91,90,15,131,13,201,95,96,53,194,233,7,225,140,36,103,30,
    69,142,8,99,37,240,21,10,23,190,6,148,247,120,234,75,0,26,197,62,94,
    252,219,203,117,35,11,32,57,177,33,88,237,149,56,87,174,20,125,136,171,
    168,68,175,74,165,71,134,139,48,27,166,77,146,158,231,83,111,229,122,60,
    211,133,230,220,105,92,41,55,46,245,40,244,102,143,54,65,25,63,161,1,
    216,80,73,209,76,132,187,208,89,18,169,200,196,135,130,116,188,159,86,
    164,100,109,198,173,186,3,64,52,217,226,250,124,123,5,202,38,147,118,
    126,255,82,85,212,207,206,59,227,47,16,58,17,182,189,28,42,223,183,170,
    213,119,248,152,2,44,154,163,70,221,153,101,155,167,43,172,9,129,22,39,
    253,19,98,108,110,79,113,224,232,178,185,112,104,218,246,97,228,251,34,
    242,193,238,210,144,12,191,179,162,241,81,51,145,235,249,14,239,107,49,
    192,214,31,181,199,106,157,184,84,204,176,115,121,50,45,127,4,150,254,
    138,236,205,93,222,114,67,29,24,72,243,141,128,195,78,66,215,61,156,180,
    /* repeat */
    151,160,137,91,90,15,131,13,201,95,96,53,194,233,7,225,140,36,103,30,
    69,142,8,99,37,240,21,10,23,190,6,148,247,120,234,75,0,26,197,62,94,
    252,219,203,117,35,11,32,57,177,33,88,237,149,56,87,174,20,125,136,171,
    168,68,175,74,165,71,134,139,48,27,166,77,146,158,231,83,111,229,122,60,
    211,133,230,220,105,92,41,55,46,245,40,244,102,143,54,65,25,63,161,1,
    216,80,73,209,76,132,187,208,89,18,169,200,196,135,130,116,188,159,86,
    164,100,109,198,173,186,3,64,52,217,226,250,124,123,5,202,38,147,118,
    126,255,82,85,212,207,206,59,227,47,16,58,17,182,189,28,42,223,183,170,
    213,119,248,152,2,44,154,163,70,221,153,101,155,167,43,172,9,129,22,39,
    253,19,98,108,110,79,113,224,232,178,185,112,104,218,246,97,228,251,34,
    242,193,238,210,144,12,191,179,162,241,81,51,145,235,249,14,239,107,49,
    192,214,31,181,199,106,157,184,84,204,176,115,121,50,45,127,4,150,254,
    138,236,205,93,222,114,67,29,24,72,243,141,128,195,78,66,215,61,156,180
};

static inline float _grad3(int hash, float x, float y, float z) {
    int h = hash & 15;
    float u = h < 8 ? x : y;
    float v = h < 4 ? y : (h==12 || h==14 ? x : z);
    return ((h&1) ? -u : u) + ((h&2) ? -v : v);
}

static inline float snoise3D(vec3 p) {
    float xin=p.x, yin=p.y, zin=p.z;
    const float F3 = 1.f/3.f, G3 = 1.f/6.f;
    float s = (xin+yin+zin)*F3;
    int i=(int)floorf(xin+s), j=(int)floorf(yin+s), k=(int)floorf(zin+s);
    float t=(i+j+k)*G3;
    float X0=i-t, Y0=j-t, Z0=k-t;
    float x0=xin-X0, y0=yin-Y0, z0=zin-Z0;
    int i1,j1,k1,i2,j2,k2;

    if (x0>=y0) {
        if (y0>=z0) {
            i1=1;j1=0;k1=0;i2=1;j2=1;k2=0;
        } else if (x0>=z0) {
            i1=1;j1=0;k1=0;i2=1;j2=0;k2=1;
        } else {
            i1=0;j1=0;k1=1;i2=1;j2=0;k2=1;
        }
    } else {
        if (y0<z0) {
            i1=0;j1=0;k1=1;i2=0;j2=1;k2=1;
        } else if (x0<z0) {
            i1=0;j1=1;k1=0;i2=0;j2=1;k2=1;
        } else {
            i1=0;j1=1;k1=0;i2=1;j2=1;k2=0;
        }
    }

    float x1=x0-i1+G3,y1=y0-j1+G3,z1=z0-k1+G3;
    float x2=x0-i2+2*G3,y2=y0-j2+2*G3,z2=z0-k2+2*G3;
    float x3=x0-1+3*G3,y3=y0-1+3*G3,z3=z0-1+3*G3;
    int ii=i&255,jj=j&255,kk=k&255;
    int gi0=_perm[ii+_perm[jj+_perm[kk]]]&15;
    int gi1=_perm[ii+i1+_perm[jj+j1+_perm[kk+k1]]]&15;
    int gi2=_perm[ii+i2+_perm[jj+j2+_perm[kk+k2]]]&15;
    int gi3=_perm[ii+1+_perm[jj+1+_perm[kk+1]]]&15;
    float n0,n1,n2,n3;
    float t0=.6f-x0*x0-y0*y0-z0*z0; n0=t0<0?0:(t0*=t0,t0*t0*_grad3(gi0,x0,y0,z0));
    float t1=.6f-x1*x1-y1*y1-z1*z1; n1=t1<0?0:(t1*=t1,t1*t1*_grad3(gi1,x1,y1,z1));
    float t2=.6f-x2*x2-y2*y2-z2*z2; n2=t2<0?0:(t2*=t2,t2*t2*_grad3(gi2,x2,y2,z2));
    float t3=.6f-x3*x3-y3*y3-z3*z3; n3=t3<0?0:(t3*=t3,t3*t3*_grad3(gi3,x3,y3,z3));
    return 32.f*(n0+n1+n2+n3);
}
